# Generated by Django 4.1.7 on 2023-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uri', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('music_file', models.CharField(blank=True, max_length=150, null=True)),
                ('image_file', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
