# Generated by Django 4.2.1 on 2023-10-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uri', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('music_filename', models.CharField(blank=True, max_length=150, null=True)),
                ('music_cover_filename', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.TextField(default='')),
                ('music_file_uri', models.CharField(blank=True, max_length=150, null=True)),
                ('music_cover_uri', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
