# Generated by Django 4.1.7 on 2023-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='artist_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
