# Generated by Django 4.1.7 on 2023-06-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0002_file_artist_name_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='http_uri',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
