# Generated by Django 4.1.7 on 2023-08-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0003_file_http_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image_file',
            new_name='music_cover_filename',
        ),
    ]
