# Generated by Django 4.1.7 on 2023-08-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0004_rename_image_file_file_music_cover_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='desc',
        ),
    ]
