# Generated by Django 4.1.7 on 2023-08-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0005_rename_description_file_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='music_file',
            new_name='music_filename',
        ),
    ]
