# Generated by Django 4.1.7 on 2023-08-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0007_file_music_cover_url_file_music_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='artist_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='http_uri',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='music_cover_filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='music_cover_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='music_file_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='music_filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uri',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
