# Generated by Django 4.1.7 on 2023-08-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_storage_service', '0008_alter_file_artist_name_alter_file_http_uri_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='http_uri',
            new_name='music_cover_uri',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='music_cover_url',
            new_name='music_file_uri',
        ),
        migrations.RemoveField(
            model_name='file',
            name='music_file_url',
        ),
    ]
